export const LOAD_PRODUCTS_SUCCESS = `LOAD_PRODUCTS_SUCCESS`;
export const ADD_PRODUCT_TO_CART = `ADD_PRODUCT_TO_CART`;
export const REMOVE_PRODUCT_FROM_CART = `REMOVE_PRODUCT_FROM_CART`;
export const HEART_THE_PRODUCT = `HEART_THE_PRODUCT`;
export const UNHEART_THE_PRODUCT = `UNHEART_THE_PRODUCT`;

export const SET_USER_DATA = `SET_USER_DATA`;
export const GET_USER_DATA = `GET_USER_DATA`;
